adding Colorado medicare exclusion list crawler
opensanctions/opensanctions pull request #1187
Opened 2024-08-26 14:05 UTC by bgmello

2024-08-28 13:47 UTC, jbothma requested changes
Thank you!

Same changes as kansas please

2024-09-01 21:05 UTC, bgmello commented
I'm getting an error while trying to create the link between the company and the entity saying it's a self referencing link. I left that part of the code commented out.

2024-09-02 10:47 UTC, jbothma commented on datasets/us/co/med_exclusions/crawler.py
> +            entity.add("npiCode", npi)
entity.add happily takes lists

```suggestion
        entity.add("npiCode", npis)
```

2024-09-02 10:47 UTC, jbothma commented on datasets/us/co/med_exclusions/crawler.py
> +        npis = re.split(r"; |& ", row.pop("npi"))
no need to change, but h.multisplit() is a common tool for this purpose

2024-09-02 10:47 UTC, jbothma commented on datasets/us/co/med_exclusions/crawler.py
> +        reinstatement_effective_date = None
or simply

```suggestion
    reinstatement_date = row.pop("reinstatement_effective_date", None)
```

2024-09-02 10:47 UTC, jbothma commented on datasets/us/co/med_exclusions/us_co_med_exclusions.yaml
> +  Section 8.076.1.7.
If we quote verbatim, it's best to indicate that with markdown quote prefixes and a link

```suggestion
  > The Department of Health Care Policy & Financing (HCPF) maintains a list of providers whose participation in
  > Health First Colorado (Colorado's Medicaid program) has been terminated for cause. A provider who has been
  > terminated for cause may not receive reimbursement under the Medicaid program. A description of the reasons
  > a provider may be terminated for cause can be found under the definition of Good Cause at 10 CCR 2505-10,
  > Section 8.076.1.7.
  
  [Provider Termination page](https://hcpf.colorado.gov/provider-termination)
```

2024-09-02 11:19 UTC, jbothma commented on datasets/us/co/med_exclusions/crawler.py
> +        # link.id = context.make_id(dba)
the link ID and company ID would end up the same unless you add something to the link

```suggestion
        link.id = context.make_id(entity.id, company.id)
```

2024-09-03 16:45 UTC, merged