adding Michigan Medicare Exclusions crawler
opensanctions/opensanctions pull request #1203
Opened 2024-09-02 11:53 UTC by bgmello

There is two multiple sanction dates in the data. I used only the first one because I'm not sure what are the others.

2024-09-04 15:05 UTC, jbothma requested changes
Thanks! Mainly missing some entities

2024-09-04 15:05 UTC, jbothma commented on datasets/us/mi/med_exclusions/crawler.py
> +        return
it looks like sometimes there's a first name but not a legal entity

2024-09-04 15:05 UTC, jbothma commented on datasets/us/mi/med_exclusions/crawler.py
> +    entity = context.make("LegalEntity")
Looks safe to be more specific

```suggestion
    entity = context.make("Company")
```

2024-09-12 18:17 UTC, bgmello commented
There are some dates I couldn't parse, I think they are an error but I'm not sure what to do in that case, do I just leave the warning?
<img width="971" alt="Screenshot 2024-09-12 at 15 17 35" src="https://github.com/user-attachments/assets/cc8e710f-c9d6-4b57-a56c-6b859e6fcecd">

2024-09-13 09:11 UTC, jbothma commented
good question.
The next step is to add a `type.date` lookup in the metadata. Any values you feel you can accurately parse yourself, you can make the `value` the date, e.g. `2023-06-27`. The rest, just make `value: null`

https://zavod.opensanctions.org/best_practices/datapatch_lookups/

2024-09-13 13:22 UTC, bgmello commented
I added the lookup but it's still showing the warnings for the non-null values.

2024-09-23 13:04 UTC, merged