Crawler for the National Assembly of Venezuela
opensanctions/opensanctions pull request #526
Opened 2024-01-18 20:40 UTC by dhdaines

Crawls members from the website extracting some info from personal pages where possible (could do better).

See: #525

2024-01-22 11:02 UTC, jbothma requested changes
very nice! thank you!

I'd suggest changing the info logs about unique IDs to debugs, the exception handler to info-level, and then adding a couple of `match` [datapatches](https://github.com/opensanctions/datapatch) for the date warnings like this

```
2024-01-22 10:46:26 [warning  ] Rejected property value        [zavod.runtime.cleaning] dataset=ve_asamblea_nacional entity_id=ve-asamblea-nacional-69be6cde3d6e13b51c55c35594c54fef93a88877 prop=birthDate value=31 de enero de 1.981
```

like this https://github.com/opensanctions/opensanctions/blob/main/datasets/_global/icij_offshoreleaks/icij_offshoreleaks.yml#L497

The thinking here is that errors and warnings end up at https://www.opensanctions.org/issues/ and I don't see them fixing them soon. Still, it's nice that they're visible.

2024-01-30 18:38 UTC, dhdaines commented
> I'd suggest changing the info logs about unique IDs to debugs, the exception handler to info-level, and then adding a couple of `match` [datapatches](https://github.com/opensanctions/datapatch) for the date warnings 

Ah, okay, I think I understand - basically we can add the unmatched values as overrides to the `lookups` in the yaml file.  There is also one member whose information is all contained in `<span>` tags so lxml concatenates it together with no whitespace :( though I think I could also special-case that in the crawler code.

2024-01-30 19:23 UTC, jbothma approved these changes

2024-01-30 19:23 UTC, jbothma commented on datasets/ve/asamblea_nacional/ve_asamblea_nacional.yml
> +prefix: ve-asamblea-nacional
```suggestion
prefix: ve-asamblea
```

2024-01-30 19:23 UTC, jbothma commented on datasets/ve/asamblea_nacional/crawler.py
> +    context.log.debug(f"Fetching front page from {context.data_url}")
```suggestion
    context.log.info(f"Fetching front page from {context.data_url}")
```

2024-01-30 19:27 UTC, merged