creating crawler for Brazil Central Bank QGP
opensanctions/opensanctions pull request #531
Opened 2024-01-19 18:04 UTC by bgmello

This PR creates the crawler for the  Brazil Central Bank QGP describe below:

The QGP, managed by the Central Bank of Brazil, is essential for regulatory 
  compliance in the financial industry. It details names of persons and entities
  facing temporary bans from offering auditing services to Central Bank-regulated institutions.
  These restrictions, often a result of penalties in administrative proceedings,
  aim to ensure the reliability and integrity of those in key auditing roles.
  The QGP reflects the Central Bank's dedication to maintaining
  stability and transparency in Brazil's financial system.

Issue https://github.com/opensanctions/crawlers/issues/16

2024-01-22 09:56 UTC, jbothma requested changes
Thanks, looks great!

I think all the comments to https://github.com/opensanctions/opensanctions/pull/519 also apply here - for the entity id, just make the prefix br-cnpj when it's companies.

2024-01-22 09:56 UTC, jbothma commented on datasets/br/bcb_prohibited/crawler.py
> +    entity.add('topics', 'corp.disqual')
For this list I think debarment is most appropriate

```suggestion
    entity.add('topics', 'debarment')
```

2024-01-22 09:56 UTC, jbothma commented on datasets/br/bcb_prohibited/crawler.py
> +        context.log.error("Tax number is neither a CPF nor CNPJ")
very nice

2024-01-22 09:56 UTC, jbothma commented on datasets/br/bcb_prohibited/crawler.py
> +        "program", "Brazil's Central Bank General Register of Persons Prohibited from Offering Auditing Services"
```suggestion
        "program", "Brazil's Central Bank General Register of Persons and Companies Prohibited from Offering Auditing Services"
```

2024-01-22 16:22 UTC, bgmello commented
Waiting for the PR #519 to be resolved so I can apply the same modifications here.

2024-01-23 12:39 UTC, bgmello commented
I made the same changes outlined on #519

2024-01-23 14:06 UTC, merged