Add slovenia debarment crawler
opensanctions/opensanctions pull request #544
Opened 2024-01-24 15:34 UTC by atehe

Closes #419  

@jbothma I crawled the dataset similar to the entities used in [aleph](https://aleph.occrp.org/datasets/8867) but the `target.nested.json` stays empty.
I was thinking it is could be because the debarment role has not been added to the dataset but the target entity (`LegalEntity`)  does not have th attribute.
can you please take a look and let me know what you think.

2024-01-24 16:55 UTC, jbothma commented
hey! I get 11048 entities, 5368 targets. Could it be that when you're exporting it's not re-generating the "store"? Sorry - I have a docs improvement that we'll merge soon that talks about that https://github.com/opensanctions/opensanctions/pull/495/files#diff-be685f78c6a9454eb7878fa369e723f2aae3430e9b013a54ef8a85edf915e57bR35

2024-01-24 17:43 UTC, atehe commented
Ah... thanks, it exports now.
Where can I add the role ,`debarment` to the dataset .
I was thinking the `UnknownLink` entity will suffice?

2024-01-24 18:13 UTC, jbothma requested changes
Just a quick look at this. I'll take a better look tomorrow.

2024-01-24 18:13 UTC, jbothma commented on datasets/si/br/crawler.py
> +    validity_link.add("object", organization)
totally see why you added the org and the link here.
in this case let's only do the legal entity, and the debarment topic, and note why these entities are debarred in the entity program property.

2024-01-25 16:30 UTC, jbothma requested changes
alright - our journalist contact has also pointed out that this is quite a complex one, but that we understand correctly. Nice job figuring it out.

I've proposed a much briefer form as the opening section to the description, and our contact provided a link to an english explanation page so we don't have to use the translated detail - we can paraphrase from the clearer website and link to it.

thanks again!

2024-01-25 16:30 UTC, jbothma commented on datasets/si/br/si_br.yml
> +  Therefore, the absence of an entity on the list does not negate the applicability of business restrictions with that entity.
Could you see if you can summarise from https://www.kpk-rs.si/en/restrictions-of-business-activities/ replace the More detail from the publisher section, and then also link to that page similarly to how I have in that section?

2024-01-25 18:08 UTC, atehe commented
The description you added is verry clear.
I've updated it with the publishers details and data source.

2024-01-26 14:41 UTC, jbothma reviewed
Thank you!

Next time please add to the appropriate collection too.

2024-01-26 14:41 UTC, jbothma commented on datasets/si/br/si_br.yml
> +  **This is a preventative restriction by Komisija za preprečevanje korupcije and implies no wrongdoing.**
```suggestion
  Slovenian public bodies and organizations may not procure from entities in which an official in that organization or their family member is a manager, legal representative, or has 5% or more ownership.
  
  This is a list of entities where such a relationship exists, and the public organization is restricted/prohibited or permitted to engage in business activities in some instances with the entity. The restricted public organization is noted in the program property of each entity. **The restriction is only on the public organization where the public official has a role - it does not apply to the entire public sector.**
  
  **This is a preventative restriction by Komisija za preprečevanje korupcije and implies no wrongdoing.**
```

2024-01-26 14:41 UTC, jbothma commented on datasets/si/br/si_br.yml
> +  [Translated and edited from https://www.kpk-rs.si/en/restrictions-of-business-activities/](https://www.kpk-rs.si/en/restrictions-of-business-activities/)
```suggestion
  ### More detail from the publisher:
  
  > As the public sector conducts business with private-sector entities, certain corruption risks are generated, especially when individuals with personal interests in the business activity are involved. To safeguard public funds from being used for private gain, legal measures, such as restrictions on business activities and prohibitions, are implemented.
  > These measures are outlined in the Integrity and Prevention of Corruption Act (IPCA) and focus on preventing corruption and avoiding conflicts of interest.
  [From https://www.kpk-rs.si/en/restrictions-of-business-activities/](https://www.kpk-rs.si/en/restrictions-of-business-activities/)
```

2024-01-26 14:41 UTC, jbothma commented on datasets/si/br/si_br.yml
> +  While the Commission emphasizes the accuracy of published data, occasional discrepancies may occur, urging users to check their completeness, accuracy and up-to-dateness with the original administr
```suggestion
  ### Data gathering process

    The data is gathered from the app [Erar](https://erar.si/doc/). It is a web application developed by the Komisija za preprečevanje korupcije to enhance transparency by allowing the public and state authorities in Slovenia to access detailed information on transactions involving public institutions and state-owned entities.
  While the Commission emphasizes the accuracy of published data, occasional discrepancies may occur, urging users to check their completeness, accuracy and up-to-dateness with the original administrator of the database before making decisions based on them. Due to such corrections, the published data may change at any time without prior notice.
```

2024-01-26 15:13 UTC, merged

2024-01-26 16:02 UTC, atehe commented
Noted JD.
Can you please confirm the appropraite collection you are referring to

2024-01-26 16:09 UTC, jbothma commented
In this case it was debarments, which was easy, because there's a debarments collection. It's not always obvious, but a lot of the time there's a direct match. https://zavod.opensanctions.org/tutorial/#add-your-crawler-to-a-collection

2024-01-26 21:38 UTC, atehe commented
Understood now, thanks