Add Hong Kong Principal Officials
opensanctions/opensanctions pull request #564
Opened 2024-02-06 23:46 UTC by atehe

2024-02-08 12:12 UTC, jbothma requested changes
Thank you! Just some small comments

2024-02-08 12:12 UTC, jbothma commented on datasets/hk/po/crawler.py
> +    position_name = member_header.split(",")[-1]
With this, does `Secretary for Culture, Sports and Tourism` become `Sports and Tourism`?

I wonder if a better way might be 

1. take member_header[1:] (perhaps tell split to only split once)
2. delete all acronymns, e.g. `re.sub("([A-Z], )*[A-Z]", "", str)` (there are bugs in that, just the idea)
3. delete all acronymns

2024-02-08 12:12 UTC, jbothma commented on datasets/hk/po/crawler.py
> +    position_name = f"{section} - {position_name.strip()}"
mmm I think `Secretary for Culture, Sports and Tourism` is a perfect position name.
I think `Directors of Bureaux - Secretary for Culture, Sports and Tourism` is more than we need. So let's rather not prefix the position name with it.

You could stick `Directors of Bureaux` in to the position description while you have it at hand.

2024-02-09 12:38 UTC, atehe commented on datasets/hk/po/crawler.py
> +    url = context.data_url.replace("index.htm", url)
thanks

2024-02-12 10:07 UTC, jbothma commented on datasets/hk/principal_officials/hk_principal_officials.yml
> +title: Principal Officals of Hong Kong
Hong Kong Principal Officials
```suggestion
title: Hong Kong Principal Officials
```

2024-02-12 10:07 UTC, merged