Adding thailand AMLO designated list crawler
opensanctions/opensanctions pull request #744
Opened 2024-04-08 14:38 UTC by bgmello

fixes opensanctions/crawler-planning#110

2024-04-09 17:10 UTC, jbothma requested changes
Very nice, thank you! A few small things. Also please take a look and address the lint issues identified in the lint workflow.

2024-04-09 17:10 UTC, jbothma commented on datasets/th/designated_person/th_designated_person.yaml
> +  Financing Act B.E. 2559 section 7
Please wrap at 80 chars

```suggestion
  Financing Act B.E. 2559 section 7
  
  According to the act:
  
    > ...[R]eporting entities and persons in possession of the assets of the designated persons [will be informed to]  Freeze the assets of the designated persons or a person acting on behalf of, or at the direction of, or an undertaking owned or controlled by such persons, directly or indirectly
```

2024-04-09 17:10 UTC, jbothma commented on datasets/th/designated_person/crawler.py
> +    entity.add("topics", "crime")
I think this is enough of a standard financial sanction to use the sanction topic.
```suggestion
    entity.add("topics", "sanction")
```

2024-04-09 19:25 UTC, bgmello commented on datasets/th/designated_person/crawler.py
> +    sanction.add("sourceUrl", url)
I also added the Notification Number to this.

2024-04-15 17:35 UTC, jbothma commented on datasets/th/designated_person/crawler.py
> +    sanction.add("sourceUrl", url)
I think that's ok - let's go with this for now.

2024-04-15 18:18 UTC, merged